###############################################################################
# Prelude
###############################################################################

# Set TREESITTER_INCDIR/TREESITTER_LIBDIR for dune; generated by configure.
# '-include' so that the first build before configure still works.
# coupling: osemgrep/Makefile
-include tree-sitter-config.mk

###############################################################################
# Main targets
###############################################################################

# TODO: add {,test} at some point
default:
	dune build _build/install/default/bin/codemap

all:
	dune build
clean:
	dune clean
test: build-test
	./test

build-test:
	dune build _build/default/src/tests/Test.exe
install:
	dune build codemap.install
	dune install codemap

.PHONY: all clean install test build-test


codemap.opam: dune-project
	dune build $@

build-docker:
	docker build -t "codemap" .
build-docker-ocaml5:
	docker build -t "codemap" --build-arg OCAML_VERSION=5.2.1 .

###############################################################################
# Developer targets
###############################################################################

# -filter semgrep
visual:
	./bin/codemap -screen_size 3 -efuns_client efuns_client -emacs_client /dev/null .
sync:
	@echo go to docs/literate/
index:
	$(MAKE) clean
	$(MAKE)
	codegraph_build -lang cmt .
