#-*- org -*-

* Last

** Last 6

*** less: start a gui/ in semgrep-pfff-libs? 

*** fix bugs with search and indexing not working

*** FUN resume layer and tool to display the region that were recently modified!

*** integrate better osemgrep, live search open Common2
and Common2.$XXX (with resolved aliasing! using ocamllsp!!)

*** FUN mix codemap and semgrep with yaml rule that returns
not only a match but also a color! so can then generate layer
from a semgrep query and for example see all the place where
we use Cap.xxx with different colors for the xxx

maybe osemgrep scan --generate_codemap_layer ?

just need a match with a rulename that carry a color?

id: layer--fork--color--red
for a rule


** Last 6 bis

*** fail to render 5a/a.y because lexical error identifier $1
so either forbid .y in codemap use_fancy_highlighting
or extend lexer

*** fail to go in goken/include/, force quit

*** fail to render xix/lib_core/commons/Chan.ml
why??

*** color differently polymorphic type, like in xix/linker/Arch.ml
get the 'instr polymorphic type in a different color than t itself

*** coloring for toml? use tree-sitter-toml that I added recently in
semgrep for SCA?

*** RELAX add .lean and Lean to Ftype.ml and codemap display list
.rkt racket (malt)

arch_ testdata/

*** fix codemap -symlinks in software-src/TAGS/1-tiny/
got exn because try to build relative path or something

*** can't parse goken/rc/unix.c :(
take forever

same pb with libmach/linux.c

^CSIGINT signal intercepted, will do some cleaning before exiting
Common.UnixExit(-130)
Raised at UCommon.main_boilerplate.(fun).default_handler.(fun) in file "libs/commons/UCommon.ml", line 105, characters 14-76
Called from Token_helpers_cpp.info_of_tok.(fun) in file "languages/cpp/menhir/token_helpers_cpp.ml", line 573, characters 13-20
Called from Token_helpers_cpp.info_of_tok.(fun) in file "languages/cpp/menhir/token_helpers_cpp.ml", line 573, characters 13-20
Called from Token_helpers_cpp.visitor_info_of_tok in file "languages/cpp/menhir/token_helpers_cpp.ml", line 398, characters 48-51
Called from Token_helpers_cpp.info_of_tok in file "languages/cpp/menhir/token_helpers_cpp.ml", line 571, characters 2-76
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 138, characters 11-31
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel.aux_toks in file "src/highlighters/highlight_cpp.ml", line 92, characters 8-19
Called from Highlight_cpp.visit_toplevel in file "src/highlighters/highlight_cpp.ml", line 156, characters 2-15
Called from Parsing.tokens_with_categ_of_file_helper in file "src/gui/Parsing.ml", line 176, characters 4-107
Called from Draw_microlevel.glyphs_of_file in file "src/gui/draw_microlevel.ml", line 210, characters 28-75
Called from Draw_microlevel.draw_content in file "src/gui/draw_microlevel.ml", line 373, characters 4-65
Called from Draw_microlevel.draw_treemap_rectangle_content_maybe in file "src/gui/draw_microlevel.ml", line 482, characters 18-53
Called from View_mainmap.paint_content_maybe_rect.(fun) in file "src/gui/view_mainmap.ml", line 93, characters 5-89
Called from View_mainmap.lazy_paint in file "src/gui/view_mainmap.ml", line 113, characters 8-54
Called from View_mainmap.paint.(fun) in file "src/gui/view_mainmap.ml", line 158, characters 20-52
Called from Gui.gmain_idle_add.(fun) in file "libs/gui/Gui.ml", line 713, characters 8-19



*** RELAX fix C/C++ parser output, use Logs not pr2
and maybe put behind a Log src so not shown by default?
or use Logs.warn?
ERROR_RECOV: found sync '}' at line 221


*** SEMI codemap: !!why codemap recompiled and on X11 get still 100%cpu on source xix?!!
it works well on the source of {codemap,codegraph,efuns}, but on xix
even with -filter mli, get 100% and not stopping and can't use C-q :(

also 100% on myocaml/

*** SEMI why 99% CPU on wayland on xix codebase?
same on xorg?

partially fixed by removing the Thread.create at the beginning
computing database

*** dupe? why take 100% CPU again :( seems to happen more on C codebase
tree-sitter C parser is wrong?

*** dupe? why can't even run codemap on xv6-riscv? already go in 100% CPU 

*** why highlighting on goken/src/lib9/utf/utf.h takes forever?
codemap -verbose, add codemap -debug to better diagnose?
add appropriate Logs in codemap or semgrep-libs ?

*** why super slow on libmach/linux.c?

*** SEMI resume mk pdf, add basic intro at least

*** LATER switch to 5.2.1 and use domains to render in parallel using many cpus!
and share parsing cache

*** LATER release on OPAM, but first need release many semgrep libs
or add option to compile codemap without tree-sitter and all of semgrep libs
maybe semgrep-light-libs


** Last 5

*** add arch_code colors for README.md, pad.org, .gitignore?

*** why codemap can't parse most .go files? lots of red!

*** why can't see content of configure script in codemap?
because no extension?


*** RELAX cleanup the code, switch to Fpath.t in model.ml
but need syncweb working first?

*** consider CLI.ml as Main.ml

*** RELAX colorize specialy capabilities in codemap!
present in AST_ocaml.ml ? present in AST_generic.ml if use
generic highlighters? need ocaml-specific highlighter?

*** untangle some of the deps to semgrep.core from codemap
because of Lang.ml, because of Naming_AST.ml depending
on semgrep.typing depending on semgrep.core, etc.

*** Makefile mode, so can visualize Makefiles
need tree-sitter-makefile? add it in codemap/languages/

*** RELAX Log src for gui event, log src for db event
but set LOG_SRCS from Arg flag callback?

and make sure default codemap does not show much
unless you set LOG_SRCS


*** still? remove use of common_parent, force single root parameter?
but I use the ability to use multiples dirs when exploring
r2c codebases so good to keep?


** Last 4

*** Can't use search anymore, blocked

*** add GHA checks, build, test, and semgrep

*** RELAX use Fpath.t, Logs, GHA, and maybe even capabilities :)

** Last 3

*** codemap on Naming_AST.ml is ugly
update to latest semgrep? don't parse the object code?

*** tree-sitter-make?
with bash embedded?

so can visualize my Makefile nicely?

fork it? still didn't fix the issue I reported?

AST_Makefile? like AST_dockerfile

*** improve Makefile visualization, finish tree-sitter-make integration

*** improve Yaml visualization, fix weird tokens generated by Emma?

*** fix yaml and codemap?
weird file position, tell Emma?

*** RELAX update codemap/efuns with better colors for Xxx_, UXxx, CapXxx

*** -filter .go, .ml[], whatever extension?

*** ---------------------------------------

*** fix visualization of files without trailine newline
for ex cant visualize jsonnet files under tests/jsonnet/ without
trailing newlines

*** seems a bit slower, or seems to require me to press C-r to force refresh
because there's no content. ex: Go on Core_result.ml, takes forever
to get the actual content displayed; you just get a big green screen.
and after C-r it comes

*** finish opam release stuff so can use codemap from semgrep!!
or use semgrep from codemap!!


** Last 2

*** problem with generated layers by codegraph_build, get ofv float exn
when trying to read the layer in codemap

test: opam switch 4.12.0 ... make index ... cm .
and see exn

*** fix codemap on our typescript code
thx to tree-sitter-typescript!

*** use tree-sitter libs for OCaml!
# update: with pfff integrated in semgrep, and osemgrep and releasing in OPAM,
# this might become easier

see Semgrep_envvars.ml
=> need to switch to tree-sitter for parsing OCaml? link tree-sitter parsers
with codemap?

Textedit.{path = ...} (was in Output.ml)

type t = private int (in Exit_code.mli)

and foo = bar [@@deriving] (was in IL.ml)
and xxx = zzz
[@@deriving ]

*** use tree-sitter libs in codemap! for TS/C++/...
tree-sitter-langs? ocaml-tree-sitter-lang repo?
so can also use codemap for C++ code!
use https://github.com/returntocorp/ocaml-tree-sitter-languages

someone from Facebook recently wanted to use ocaml-tree-sitter for Pyre :)

*** weird bug on deep-semgrep/src/core/sig/Name.ml where if
last line does not contain a newline then no display

** Last 1

*** use model-view-update to simplify the code?

*** fix efuns, codemap, emacs config, macos config, etc.

**** efuns: Thread.kill not available and all those
second cursor errors

**** codemap: no more regexps displayed, just the leading /
because split_info? need put back in stream of tokens?

*** RELAX move arch_code.* out of pfff, move h_visualization/ too
put in codemap

*** RELAX maybe move highlight_code.ml in codemap 
so easy to change color constructor?

*** RELAX add highlight_code.ml to Visual.mw?

*** codemap not highlighing correctly fields in visitors
in Analyze_pattern.ml

*** move all pfff/todo.txt in codemap/todo.txt


*** make it work on MacOS!
seems to display at the beginning, especially id don't add -screen_size
and use default, but after it disappears

*** rely on Naming_AST.ml to uncomment code in Highlight_AST.ml
for better color for params, locals, globals (test on C code),
but also improve method vs func, etc. 
Fix all the commented-out code.

*** switch to lablgtk3?
even gtk4 lately.

*** factorize AST-based lang-specific highlighters in Highlight_AST.ml?
Java,
Python,
etc.
so can remove more visitor_xxx.ml ?

*** switch to revery? more portable? better code orga? FRP/ELM wins?

*** codemap on parser_ruby.dyp does not work anymore

